### ISSUE TITLE
Add CI and publish image to dockerhub 

### ISSUE THREAD

**Issue by jldec** [projectriff-demo/inventory-management#20]
[Demo instructions](https://github.com/projectriff-demo/demo#build-inventory-api-app) refer to the [projectriffdemo/inventory-api:v001](https://hub.docker.com/r/projectriffdemo/inventory-api/tags) image on dockerhub. This image is currently published manually.

**Comment by fbiville** [comment]
This has [already been done](https://github.com/projectriff-demo/inventory-management/commit/8f112f893c7a28d54f688b35e7d76cc553c832d7#diff-a08f0808f9c737cf06c30228b9c8f90e) (I forgot to create a CI issue for this repo, my bad).

See [here](https://github.com/projectriff-demo/inventory-management/blob/c0cbdf4fd94f4cca424979b843568df2d5aaed98/.github/workflows/backend-ci.yaml#L33) for backend, [here](https://github.com/projectriff-demo/inventory-management/blob/c0cbdf4fd94f4cca424979b843568df2d5aaed98/.github/workflows/frontend-ci.yaml#L50) for frontend.
